version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn start:server
    environment:
      NODE_ENV: development
    ports:
      - '5000:5000'
    volumes:
      - .:/app